# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_in_meters', models.FloatField()),
                ('weight_in_kg', models.FloatField()),
                ('measured_at', models.DateField()),
            ],
        ),
    ]
